name: Build and Push Docker Image to Gitea Registry

# This workflow is intended for Gitea Actions, not GitHub Actions.
# It assumes the runner environment has git and docker installed.

on:
  push:
    branches: [ main ] # Trigger on push to main branch in Gitea

env:
  GITEA_REGISTRY: cr.irrh.ca
  GITEA_IMAGE_NAME: boredenchilada/al4-hybridanalysis
  # GITEA_REPO_URL is provided by Gitea Actions runner environment
  # GITEA_SHA is provided by Gitea Actions runner environment

jobs:
  build-and-push-gitea:
    runs-on: ubuntu-latest # This label must match your Gitea runner's label

    steps:
      # Manual Checkout using git commands provided by Gitea runner env
      - name: Checkout repository
        run: |
          echo "Checking out commit $GITEA_SHA from $GITEA_REPO_URL"
          # Clean workspace first
          rm -rf ./* || true 
          rm -rf ./.??* || true
          # Clone and checkout specific commit
          git clone $GITEA_REPO_URL . 
          git checkout $GITEA_SHA
          echo "Checkout complete."

      # Get version from service_manifest.yml
      - name: Get version from service_manifest.yml
        id: get_version
        run: |
          if [ ! -f service_manifest.yml ]; then
            echo "Error: service_manifest.yml not found!"
            exit 1
          fi
          VERSION=$(grep "^version:" service_manifest.yml | cut -d' ' -f2)
          if [ -z "$VERSION" ]; then
            echo "Error: Could not extract version from service_manifest.yml"
            exit 1
          fi
          echo "Extracted version: $VERSION"
          # Gitea Actions uses ::set-output name=...::value
          echo "::set-output name=version::$VERSION"

      # Log in to Gitea Container Registry
      - name: Log in to Gitea Container registry
        run: |
          echo "Logging into Gitea Registry: ${{ env.GITEA_REGISTRY }}"
          # Requires GITEAUSERNAME and GITEAPASSWORD secrets in Gitea repository/org settings
          echo ${{ secrets.GITEAPASSWORD }} | docker login ${{ env.GITEA_REGISTRY }} -u ${{ secrets.GITEAUSERNAME }} --password-stdin
          echo "Login successful."

      # Build and push Docker image to Gitea Registry
      - name: Build and push Docker image to Gitea
        run: |
          IMAGE_TAG="${{ env.GITEA_REGISTRY }}/${{ env.GITEA_IMAGE_NAME }}:${{ steps.get_version.outputs.version }}"
          echo "Building image: $IMAGE_TAG"
          docker build -t "$IMAGE_TAG" .
          echo "Pushing image: $IMAGE_TAG"
          docker push "$IMAGE_TAG"
          echo "Push complete."

      # Logout is good practice
      - name: Log out from Gitea Container registry
        if: always() # Run even if previous steps fail
        run: |
          echo "Logging out from Gitea Registry."
          docker logout ${{ env.GITEA_REGISTRY }}