name: Sync to Gitea and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITEA_REGISTRY: cr.irrh.ca
  GITEA_IMAGE_NAME: boredenchilada/al4-hybridanalysis
  GITEA_REPO: https://cr.irrh.ca/boredenchilada/AL4-Hybrid-Analysis.git

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      # Get version from service_manifest.yml
      - name: Get version from service_manifest.yml
        id: get_version
        run: |
          VERSION=$(grep "^version:" service_manifest.yml | cut -d' ' -f2)
          echo "::set-output name=version::$VERSION"

      # Push code to Gitea repository
      - name: Push code to Gitea
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add Gitea remote using token authentication
          git remote add gitea https://${{ secrets.GITEAUSERNAME }}:${{ secrets.GITEAPASSWORD }}@cr.irrh.ca/boredenchilada/AL4-Hybrid-Analysis.git
          
          # Force push to Gitea
          git push -f gitea main
          
          # Push tags to Gitea
          git push -f gitea --tags

      # Push to Gitea Container Registry
      - name: Log in to Gitea Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GITEA_REGISTRY }}
          username: ${{ secrets.GITEAUSERNAME }}
          password: ${{ secrets.GITEAPASSWORD }}

      - name: Build and push Docker image to Gitea
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.GITEA_REGISTRY }}/${{ env.GITEA_IMAGE_NAME }}:${{ steps.get_version.outputs.version }}